---
output: hugodown::md_document
# Documentation: https://sourcethemes.com/academic/docs/managing-content/

title: "blah"
subtitle: ""
summary: ""
authors: []
tags: []
categories: []
date: 2020-06-09"
lastmod: 2020-06-09
featured: false
draft: false

# Featured image
# To use, add an image named `featured.jpg/png` to your page's folder.
# Focal points: Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.
image:
  caption: ""
  focal_point: ""
  preview_only: false

# Projects (optional).
#   Associate this post with one or more of your projects.
#   Simply enter your project's folder or file name without extension.
#   E.g. `projects = ["internal-project"]` references `content/project/deep-learning/index.md`.
#   Otherwise, set `projects = []`.
projects: []
---

```{r echo=FALSE}
library(ggplot2)
oplot <- ggplot(Orange, aes(x = age, 
                   y = circumference, 
                   colour = Tree)) +
  geom_point() +
  geom_line() +
  guides(colour = FALSE) +
  theme_bw()
oplot
```

## Highcharter

```{r echo=FALSE, warning=FALSE, message=FALSE}
htmltools::suppressDependencies("jquery")
library(highcharter)
hchart(Orange, "line", hcaes(x = age, y = circumference, group = Tree))
```

# DT

```{r echo=FALSE, warning=FALSE, message=FALSE}
htmltools::suppressDependencies("jquery")
library(DT)
datatable(Orange)
```
